import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/shared/components/ui/sidebar";
import AppSideBar from "@/features/sidebar/app.sidebar";
import Header from "@/features/header/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex flex-col h-screen w-full">
            <Header />
            <div className="flex flex-1">
              <AppSideBar />
              <main className="flex-1 p-10">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
