// <auto-generated />
using System;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    partial class FileServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("media_assets", (string)null);

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.Assets.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("PREVIEW");
                });

            modelBuilder.Entity("FileService.Domain.Assets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("VIDEO");
                });

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.StorageKey", "FinalKey", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("value");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.ToJson("final_key");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.StorageKey", "RawKey", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("value");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.ToJson("raw_key");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasColumnType("integer")
                                .HasColumnName("expected_chunks_count");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.ToJson("media_data");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasColumnType("text")
                                        .HasColumnName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.MediaOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_id");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.ToJson("owner");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("FinalKey");

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("RawKey")
                        .IsRequired();
                });

            modelBuilder.Entity("FileService.Domain.Assets.VideoAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.StorageKey", "HlsRootKey", b1 =>
                        {
                            b1.Property<Guid>("VideoAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("value");

                            b1.HasKey("VideoAssetId");

                            b1.ToTable("media_assets");

                            b1.ToJson("hls_root_key");

                            b1.WithOwner()
                                .HasForeignKey("VideoAssetId");
                        });

                    b.Navigation("HlsRootKey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
